
package ipcb.proyecto2ydl.tablero;

import excepciones.ListaException;
import ipcb.proyecto2ydl.tablero.Archivo;
import ipcb.proyecto2ydl.tablero.Tablero;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import linkedlist.LinkedListY;

/**
 *
 * @author yenni
 */
public class AdmiTableros extends javax.swing.JFrame {

    /**
     * Creates new form AdmiTableros
     */
    private final Archivo<LinkedListY<Tablero>> archivo;
    private final JFrame pestanaAnterior;
    private CreadorTableros creadorTableros;
    private LinkedListY<Tablero> listaTableros;
    private ColectorTableros colectorTableros;
    static final String ARCHIVO_TABLEROS = "tableros.data";
    
    public AdmiTableros(JFrame pestanaAnterior) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pestanaAnterior = pestanaAnterior;
        
        archivo = new Archivo<>();
        this.listaTableros = archivo.abrirArchivoBin(ARCHIVO_TABLEROS, new LinkedListY<>());
        this.creadorTableros = new CreadorTableros(this, listaTableros);
        this.colectorTableros = new ColectorTableros(this, listaTableros);
    }

    public ColectorTableros getColector(){
        return this.colectorTableros;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArchivo = new javax.swing.JTextArea();
        bCargar = new javax.swing.JButton();
        bCrearTab = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bAdministrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(42, 6, 6));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GENERADOR DE TABLEROS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 160));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        displayArchivo.setBackground(new java.awt.Color(102, 51, 0));
        displayArchivo.setColumns(20);
        displayArchivo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        displayArchivo.setForeground(new java.awt.Color(255, 255, 255));
        displayArchivo.setRows(5);
        jScrollPane1.setViewportView(displayArchivo);

        bCargar.setBackground(new java.awt.Color(81, 4, 4));
        bCargar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bCargar.setForeground(new java.awt.Color(255, 255, 255));
        bCargar.setText("Cargar Archivo");
        bCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarActionPerformed(evt);
            }
        });

        bCrearTab.setBackground(new java.awt.Color(81, 4, 4));
        bCrearTab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bCrearTab.setForeground(new java.awt.Color(255, 255, 255));
        bCrearTab.setText("Crear Tablero");
        bCrearTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearTabActionPerformed(evt);
            }
        });

        bGuardar.setBackground(new java.awt.Color(81, 4, 4));
        bGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bGuardar.setForeground(new java.awt.Color(255, 255, 255));
        bGuardar.setText("GUARDAR");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bAtras.setBackground(new java.awt.Color(255, 0, 0));
        bAtras.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bAtras.setForeground(new java.awt.Color(255, 255, 255));
        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bAdministrar.setBackground(new java.awt.Color(81, 4, 4));
        bAdministrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bAdministrar.setForeground(new java.awt.Color(255, 255, 255));
        bAdministrar.setText("Administar Tableros");
        bAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdministrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(bAdministrar)
                        .addGap(100, 100, 100)
                        .addComponent(bCrearTab, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCrearTab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 900, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarActionPerformed
        String textoLeido = archivo.abrirArchivo(archivo.getPath());
        displayArchivo.setText(textoLeido);
    }//GEN-LAST:event_bCargarActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        this.setVisible(false);
        pestanaAnterior.setVisible(true);
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        int sizeInicial = listaTableros.getSize();
        archivo.guardarTableros(listaTableros, displayArchivo.getText());
        listaTableros.verContent();
        int sizeFinal = listaTableros.getSize();
        boolean guardadoExitoso = archivo.guardarArchivoBin(ARCHIVO_TABLEROS, listaTableros);
        if(guardadoExitoso){
            JOptionPane.showMessageDialog(null, "Se han guardado exitosamente "
                    + (sizeFinal-sizeInicial) + " archivos de tableros");
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bCrearTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearTabActionPerformed
        this.setVisible(false);
        creadorTableros.setVisible(true);
    }//GEN-LAST:event_bCrearTabActionPerformed

    private void bAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdministrarActionPerformed
        this.setVisible(false);
        colectorTableros.inicializar("TABLERO GUARDADOS");
        colectorTableros.actualizar();
    }//GEN-LAST:event_bAdministrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdministrar;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bCargar;
    private javax.swing.JButton bCrearTab;
    private javax.swing.JButton bGuardar;
    private javax.swing.JTextArea displayArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
