
package ipcb.proyecto2ydl.tablero;

import ipcb.proyecto2ydl.admiPlayers.DisplayPersonajes;
import ipcb.proyecto2ydl.menus.BtnUtil;
import ipcb.proyecto2ydl.partida.InicializadorPartida;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import linkedlist.LinkedListY;

/**
 *
 * @author yenni
 */
public class ColectorTableros extends javax.swing.JFrame {

    /**
     * Creates new form ColectorTableros
     */
    private JFrame pestanaAnterior;
    private Tablero currentSelectionTab;
    private LinkedListY<Tablero> listaTableros;
    
    public ColectorTableros(JFrame pestanaAnterior, LinkedListY<Tablero> listaTableros) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pestanaAnterior = pestanaAnterior;
        bSeleccion.setVisible(false);
        this.listaTableros = listaTableros;
    }
    
    public void inicializar(String displayTitulo){
        this.setVisible(true);
        titulo.setText(displayTitulo);
        //if(selectionMode){
            //bSeleccion.setVisible(true);
        //}else{
            bSeleccion.setVisible(false);
        //}
    }
    //ARREGLAR AQUI
    private DisplayPersonajes admiPersonajes;
    public void setSelectionMode(String displayTitulo, DisplayPersonajes admiPersonajes){
        bAtras.setVisible(false);
        BtnUtil btnU = new BtnUtil();
        btnU.resetButton(bSeleccion);
        actualizar();
        this.setVisible(true);
        titulo.setText(displayTitulo);
        bSeleccion.setVisible(true);
        //para evitar que se haga dos veces se tiene que reiniciar el boton
        bSeleccion.addActionListener((ActionEvent e) -> {
            //anadimos el evento de los botones
            try {
                int tableroNo = (Integer.parseInt(seleccion.getText())) - 1;
                currentSelectionTab = listaTableros.getContenido(tableroNo);
                //AQUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                InicializadorPartida initPartida = new InicializadorPartida(null, 
                        currentSelectionTab, admiPersonajes.getSelectionPlayers());
                //String nickname = JOptionPane.showInputDialog(null, "Ingresa el nombre del jugador");
                //Partida partida = new Partida(null, currentSelectionTab,
                       // admiPersonajes.getSelectionPlayers(), nickname);
                this.setVisible(false);
                initPartida.setVisible(true);
            } catch (Exception ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(null, ex);
            }
        });
    }

    //TRABAJANDO AQUI****************************************
    public void actualizar(){
        String nombresTab="";
        try {
        for (int i = 0; i < listaTableros.getSize(); i++) {
            
                Tablero tablero = listaTableros.getContenido(i);
                nombresTab += " "  + (i+1) + " " +tablero.getId() + "\n";
        }} catch (Exception e) {
            }
        displayTableros.setText(nombresTab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        seleccion = new javax.swing.JTextField();
        bPrevisualizar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTableros = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bSeleccion = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(42, 6, 6));

        titulo.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("DISPLAY TITULO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titulo)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 140));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        seleccion.setBackground(new java.awt.Color(153, 153, 153));
        seleccion.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        bPrevisualizar.setBackground(new java.awt.Color(51, 0, 0));
        bPrevisualizar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bPrevisualizar.setForeground(new java.awt.Color(255, 255, 255));
        bPrevisualizar.setText("Previsualizar");
        bPrevisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrevisualizarActionPerformed(evt);
            }
        });

        bEliminar.setBackground(new java.awt.Color(51, 0, 0));
        bEliminar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(255, 255, 255));
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bAtras.setBackground(new java.awt.Color(255, 0, 0));
        bAtras.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bAtras.setForeground(new java.awt.Color(255, 255, 255));
        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        displayTableros.setEditable(false);
        displayTableros.setBackground(new java.awt.Color(255, 255, 255));
        displayTableros.setColumns(20);
        displayTableros.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        displayTableros.setForeground(new java.awt.Color(0, 0, 0));
        displayTableros.setRows(5);
        jScrollPane1.setViewportView(displayTableros);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FILTROS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Seleccion:");

        bSeleccion.setBackground(new java.awt.Color(51, 0, 0));
        bSeleccion.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        bSeleccion.setText("Seleccionar");
        bSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bPrevisualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAtras)
                    .addComponent(jLabel4)
                    .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPrevisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        pestanaAnterior.setVisible(true);
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bPrevisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrevisualizarActionPerformed
        try {
            int tableroNo = (Integer.parseInt(seleccion.getText())) - 1;
            Tablero tablero = listaTableros.getContenido(tableroNo);
            JOptionPane.showMessageDialog(null, tablero.getElementosTxt());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bPrevisualizarActionPerformed

    private void bSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeleccionActionPerformed

    }//GEN-LAST:event_bSeleccionActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        try {
            int tableroNo = (Integer.parseInt(seleccion.getText())) - 1;
            listaTableros.eliminar(tableroNo);
            Archivo<LinkedListY<Tablero>> archivo = new Archivo<>();
            archivo.guardarArchivoBin(AdmiTableros.ARCHIVO_TABLEROS, listaTableros);
            JOptionPane.showMessageDialog(null, "Se ha eliminado el tablero " + (tableroNo+1));
            actualizar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bPrevisualizar;
    private javax.swing.JButton bSeleccion;
    private javax.swing.JTextArea displayTableros;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField seleccion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
