package ipcb.proyecto2ydl.tablero;

import excepciones.LecturaException;
import excepciones.TableroException;
import ipcb.proyecto2ydl.tablero.*;
import java.util.Date;
import javax.swing.*;
import linkedlist.LinkedListY;

/**
 *
 * @author yenni
 */
public class CreadorTableros extends javax.swing.JFrame {

    /**
     * Creates new form CreadorTableros
     */
    private final AdmiTableros pestanaAnterior;
    private CrearTableroLogic creadorT;
    private String seleccionCas, currentId;
    private LinkedListY<Tablero> listaTableros;

    public CreadorTableros(AdmiTableros pestanaAnterior, LinkedListY<Tablero> listaTableros) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pestanaAnterior = pestanaAnterior;
        this.listaTableros = listaTableros;
        seleccionCas = "ninguna";
        creadorT = new CrearTableroLogic();
        ocultarDatos();
    }

    public final void ocultarDatos(){
        displayTab.removeAll();
        userId.setText("");
        dimX.setText("");
        dimY.setText("");
        bSave.setVisible(false);
        bUse.setVisible(false);
        bPlanicie.setVisible(false);
        bAgua.setVisible(false);
        bArbol.setVisible(false);
        bLava.setVisible(false);
    }
    public final void mostrarDatos(){
        bPlanicie.setVisible(true);
        bAgua.setVisible(true);
        bArbol.setVisible(true);
        bLava.setVisible(true);
        bSave.setVisible(true);
    }
    public final void displayUseTab(){
        bUse.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dimX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dimY = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        displayTab = new javax.swing.JPanel();
        bPlanicie = new javax.swing.JButton();
        bAgua = new javax.swing.JButton();
        bArbol = new javax.swing.JButton();
        bLava = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bUse = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        userId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(42, 6, 6));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESTUDIO DE TABLEROS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 140));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DIMENSIONES");

        dimX.setBackground(new java.awt.Color(153, 153, 153));
        dimX.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("X");

        dimY.setBackground(new java.awt.Color(153, 153, 153));
        dimY.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        bAceptar.setBackground(new java.awt.Color(0, 204, 0));
        bAceptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bAceptar.setForeground(new java.awt.Color(0, 0, 0));
        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        displayTab.setBackground(new java.awt.Color(30, 0, 0));

        javax.swing.GroupLayout displayTabLayout = new javax.swing.GroupLayout(displayTab);
        displayTab.setLayout(displayTabLayout);
        displayTabLayout.setHorizontalGroup(
            displayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        displayTabLayout.setVerticalGroup(
            displayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        bPlanicie.setBackground(new java.awt.Color(102, 102, 102));
        bPlanicie.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bPlanicie.setForeground(new java.awt.Color(255, 255, 255));
        bPlanicie.setText("Planicie");
        bPlanicie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlanicieActionPerformed(evt);
            }
        });

        bAgua.setBackground(new java.awt.Color(0, 0, 102));
        bAgua.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bAgua.setForeground(new java.awt.Color(255, 255, 255));
        bAgua.setText("Agua");
        bAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAguaActionPerformed(evt);
            }
        });

        bArbol.setBackground(new java.awt.Color(0, 153, 51));
        bArbol.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bArbol.setForeground(new java.awt.Color(255, 255, 255));
        bArbol.setText("Arbol");
        bArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArbolActionPerformed(evt);
            }
        });

        bLava.setBackground(new java.awt.Color(153, 0, 0));
        bLava.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bLava.setForeground(new java.awt.Color(255, 255, 255));
        bLava.setText("Lava");
        bLava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLavaActionPerformed(evt);
            }
        });

        bSave.setBackground(new java.awt.Color(51, 0, 0));
        bSave.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bSave.setForeground(new java.awt.Color(255, 255, 255));
        bSave.setText("Guardar Tablero");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bUse.setBackground(new java.awt.Color(51, 0, 0));
        bUse.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bUse.setForeground(new java.awt.Color(255, 255, 255));
        bUse.setText("Usar este tablero");

        bAtras.setBackground(new java.awt.Color(255, 0, 0));
        bAtras.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bAtras.setForeground(new java.awt.Color(255, 255, 255));
        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID");

        userId.setBackground(new java.awt.Color(153, 153, 153));
        userId.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dimX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dimY, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(displayTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bPlanicie, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bLava, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bUse, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(dimX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(dimY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bPlanicie, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bLava, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bUse, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bAtras)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try {
            Dimensiones dimensiones = creadorT.leerDimensiones(dimX, dimY);
            currentId = userId.getText();
            if(!currentId.equals("")){
                mostrarDatos();
                displayTab.removeAll();
                creadorT.inicializarCreador(dimensiones, displayTab);
            }else{
                JOptionPane.showMessageDialog(null, "Tienes que ingresar un id valido");
            }
        } catch (LecturaException  e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        this.ocultarDatos();
        this.setVisible(false);
        pestanaAnterior.setVisible(true);
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bPlanicieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlanicieActionPerformed
        creadorT.setSeleccionCasilla("planicie");
    }//GEN-LAST:event_bPlanicieActionPerformed

    private void bAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAguaActionPerformed
        creadorT.setSeleccionCasilla("agua");
    }//GEN-LAST:event_bAguaActionPerformed

    private void bArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArbolActionPerformed
        creadorT.setSeleccionCasilla("arbol");
    }//GEN-LAST:event_bArbolActionPerformed

    private void bLavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLavaActionPerformed
        creadorT.setSeleccionCasilla("lava");
    }//GEN-LAST:event_bLavaActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        Tablero tablero = new Tablero(currentId, creadorT.getContentTabCreado());
        listaTableros.add(tablero);
        ocultarDatos();
        Archivo<LinkedListY<Tablero>> archivo = new Archivo<>();
        archivo.guardarArchivoBin(pestanaAnterior.ARCHIVO_TABLEROS, listaTableros);
        JOptionPane.showMessageDialog(null, "Se ha guardado el tablero" + currentId);
    }//GEN-LAST:event_bSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAgua;
    private javax.swing.JButton bArbol;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bLava;
    private javax.swing.JButton bPlanicie;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bUse;
    private javax.swing.JTextField dimX;
    private javax.swing.JTextField dimY;
    private javax.swing.JPanel displayTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField userId;
    // End of variables declaration//GEN-END:variables
}
