
package ipcb.proyecto2ydl.menus;


import javax.swing.ImageIcon;

/**
 *
 * @author yenni
 */
public class InterfazInicio extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInicio
     */
    private MenuPrincipal menuPrincipal;
    public InterfazInicio() {
        initComponents();
        this.setLocationRelativeTo(null); //para centrar la pantalla
        initLogo(); 
        menuPrincipal = new MenuPrincipal();
    }
    
    private void initLogo(){
        ImgUtil imgU = new ImgUtil();
        ImageIcon logoImg = imgU.getImgAEscala("/images/logo.png", logo.getWidth(), logo.getHeight());
        logo.setIcon(logoImg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalDisplay = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();
        bInicio = new javax.swing.JButton();
        bCreditos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        generalDisplay.setBackground(new java.awt.Color(0, 0, 0));

        bExit.setBackground(new java.awt.Color(204, 0, 0));
        bExit.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        bExit.setForeground(new java.awt.Color(255, 255, 255));
        bExit.setText("SALIR");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        bInicio.setBackground(new java.awt.Color(0, 0, 102));
        bInicio.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        bInicio.setForeground(new java.awt.Color(255, 255, 255));
        bInicio.setText("INICIAR");
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });

        bCreditos.setBackground(new java.awt.Color(0, 0, 102));
        bCreditos.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        bCreditos.setForeground(new java.awt.Color(255, 255, 255));
        bCreditos.setText("Creditos");
        bCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreditosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generalDisplayLayout = new javax.swing.GroupLayout(generalDisplay);
        generalDisplay.setLayout(generalDisplayLayout);
        generalDisplayLayout.setHorizontalGroup(
            generalDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalDisplayLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(generalDisplayLayout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        generalDisplayLayout.setVerticalGroup(
            generalDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalDisplayLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(generalDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generalDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generalDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
        this.setVisible(false);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_bInicioActionPerformed

    private void bCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCreditosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreditos;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bInicio;
    private javax.swing.JPanel generalDisplay;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
