
package ipcb.proyecto2ydl.partida;

import ipcb.proyecto2ydl.characters.Jugable;
import ipcb.proyecto2ydl.tablero.Tablero;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author yenni
 */
public class Partida extends javax.swing.JFrame {

    /**
     * Creates new form Partida
     */
    private PartidaLogic logic;
    private JFrame pestanaAnterior;
    private Tablero tablero;
    private Jugable[] personajes;
    private int dificultad;
    public Partida(Tablero tablero, Jugable[] personajes, int dificultad) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tablero = tablero;
        this.personajes = personajes;
        this.dificultad = dificultad;
        logic = new PartidaLogic(this);
        logic.initGame();
        this.dificultad = dificultad;
    }
    public void setPestanaAnterior(JFrame pestanaAnterior){
        this.pestanaAnterior = pestanaAnterior;
    }
    public void setNickname(String nicknamePlayer){
        
    }
    public int getDificultad(){
        return dificultad;
    }

    public Tablero getTablero() {
        return tablero;
    }

    public Jugable[] getPersonajes() {
        return personajes;
    }

    public JPanel getDisplayGame() {
        return displayGame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayGame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout displayGameLayout = new javax.swing.GroupLayout(displayGame);
        displayGame.setLayout(displayGameLayout);
        displayGameLayout.setHorizontalGroup(
            displayGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        displayGameLayout.setVerticalGroup(
            displayGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(displayGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 620, 590));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -30, 1160, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayGame;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
